name: runner
on:
  workflow_dispatch:
      
jobs:
  run-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-name: [JB0,JB1,JB2,JB3,JB4,JB5,JB6,JB7,JB8,JB9,JB10,JB11,JB12,JB13,JB14,JB15,JB16,JB17,JB18,JB19]
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          java -jar myworker.jar
